openapi: 3.0.0
servers:
  - url: TD2.com
info:
  version: "latest"
  title: PROG3 - TD2
paths:
  /matches:
    get:
      tags:
        - Match
      summary: get all match
      operationId: getMatches
      responses:
        '200':
          description: List of matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
        '500':
          description: Internal server error
  /teams:
    get:
      tags:
        - Team
      summary: get all team
      operationId: getTeams
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '500':
          description: Internal server error
  /players:
    get:
      tags:
        - Player
      summary: get all player
      operationId: getplayers
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error

components:
  schemas:
    Player:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Team:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'
        sponsor:
          type: array
          items:
            $ref: '#/components/schemas/Sponsor'
    NewTeam:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    Sponsor:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Match:
      properties:
        team1:
          allOf:
            - $ref: '#/components/schemas/NewTeam'
        team2:
          allOf:
            - $ref: '#/components/schemas/NewTeam'
        datetime:
          type: string
